name: Validate, Evaluate and Score locally

on:
  pull_request:

jobs:
  luna-ml:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout latest code
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"
    - name: 
      run: |
        git fetch origin $GITHUB_BASE_REF
        echo "-------------"
        git diff origin/$GITHUB_BASE_REF..HEAD
        echo "-------------"

        #echo "GITHUB_SHA = ${{ github.sha }}"
        #echo "PR_HEAD_SHA = ${{ github.event.pull_request.head.sha }}"
    - uses: luna-ml/luna-action@main
