name: Validate, Evaluate and Score locally

on:
  pull_request:

jobs:
  luna-ml:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout latest code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"
    - name: Setup KIND (kubernetes in docker)
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.9.0"
    - uses: luna-ml/luna-action@main
