name: Validate, Evaluate and Score locally

on:
  pull_request:

jobs:
  luna-ml:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout latest code
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"
    - name: 
      run: |
        git remote -vv
        git branch -vv
        git fetch origin $GITHUB_BASE_REF
        git fetch
        git show-ref --head
        echo "GITHUB_BASE_REF=$GITHUB_BASE_REF"
        BASE_COMMIT=`git rev-parse --verify origin/$GITHUB_BASE_REF`
        echo "Base commit = $BASE_COMMIT"
        echo "GITHUB_SHA = ${{ github.sha }}"
        echo "PR_HEAD_SHA = ${{ github.event.pull_request.head.sha }}"
        
        # actual commit in pr branch
        CURRENT_COMMIT=${{ github.event.pull_request.head.sha }}
        git diff --merge-base ${GITHUB_SHA} ${BASE_COMMIT}..${CURRENT_COMMIT}

        
