name: Validate, Evaluate and Score locally

on:
  pull_request:

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout latest code
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"
    - name: 
      run: |
        echo "GITHUB_BASE_REF=$GITHUB_BASE_REF"
        BASE_COMMIT=`git rev-parse --verify $GITHUB_BASE_REF`
        CURRENT_COMMIT=$GITHUB_SHA
        git diff ${BASE_COMMIT}...${CURRENT_COMMIT}
        
