name: Submit changes to remote luna ml server

on:
  push:
    branches:
      - main

jobs:
  luna-ml-submit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout latest code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"
    - uses: luna-ml/luna-action@main
      with:
        access-token: ${{ secrets.LUNA_GH_ACCESS_TOKEN }}
